name: build

on:
  push:
    branches:
      - test2

jobs:
  # macOS
  macos-acr:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - x86_64
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install pkg-config with Homebrew
      run: brew install pkg-config
    - name: Packaging
      env:
        ARCHFLAGS: '-arch ${{ matrix.arch }}'
        CC: gcc -arch ${{ matrix.arch }}
      run: make -C dist/macos
    - name: Pub
      uses: actions/upload-artifact@v4
      with:
        path: dist/macos/*.pkg
        name: macos-acr-${{ matrix.arch }}
